/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Shopping Project API
 * Shopping Project API documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  BooleanServiceResult,
  RedisCacheRequest,
  StringServiceResult
} from '../generated.schemas';





export const getApiV1CacheKey = (
    key: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StringServiceResult>> => {
    
    
    return axios.get(
      `/api/v1/Cache/${key}`,options
    );
  }




export const getGetApiV1CacheKeyQueryKey = (key?: string,) => {
    return [
    `/api/v1/Cache/${key}`
    ] as const;
    }

    
export const getGetApiV1CacheKeyQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CacheKey>>, TError = AxiosError<StringServiceResult>>(key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CacheKey>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CacheKeyQueryKey(key);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CacheKey>>> = ({ signal }) => getApiV1CacheKey(key, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(key), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CacheKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CacheKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CacheKey>>>
export type GetApiV1CacheKeyQueryError = AxiosError<StringServiceResult>


export function useGetApiV1CacheKey<TData = Awaited<ReturnType<typeof getApiV1CacheKey>>, TError = AxiosError<StringServiceResult>>(
 key: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CacheKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CacheKey>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CacheKey>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CacheKey<TData = Awaited<ReturnType<typeof getApiV1CacheKey>>, TError = AxiosError<StringServiceResult>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CacheKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CacheKey>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CacheKey>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CacheKey<TData = Awaited<ReturnType<typeof getApiV1CacheKey>>, TError = AxiosError<StringServiceResult>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CacheKey>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CacheKey<TData = Awaited<ReturnType<typeof getApiV1CacheKey>>, TError = AxiosError<StringServiceResult>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CacheKey>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CacheKeyQueryOptions(key,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteApiV1CacheKey = (
    key: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BooleanServiceResult>> => {
    
    
    return axios.delete(
      `/api/v1/Cache/${key}`,options
    );
  }



export const getDeleteApiV1CacheKeyMutationOptions = <TError = AxiosError<BooleanServiceResult>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CacheKey>>, TError,{key: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CacheKey>>, TError,{key: string}, TContext> => {

const mutationKey = ['deleteApiV1CacheKey'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1CacheKey>>, {key: string}> = (props) => {
          const {key} = props ?? {};

          return  deleteApiV1CacheKey(key,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1CacheKeyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1CacheKey>>>
    
    export type DeleteApiV1CacheKeyMutationError = AxiosError<BooleanServiceResult>

    export const useDeleteApiV1CacheKey = <TError = AxiosError<BooleanServiceResult>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CacheKey>>, TError,{key: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1CacheKey>>,
        TError,
        {key: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1CacheKeyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postApiV1CacheSet = (
    redisCacheRequest: RedisCacheRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BooleanServiceResult>> => {
    
    
    return axios.post(
      `/api/v1/Cache/set`,
      redisCacheRequest,options
    );
  }



export const getPostApiV1CacheSetMutationOptions = <TError = AxiosError<BooleanServiceResult>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CacheSet>>, TError,{data: RedisCacheRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CacheSet>>, TError,{data: RedisCacheRequest}, TContext> => {

const mutationKey = ['postApiV1CacheSet'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CacheSet>>, {data: RedisCacheRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CacheSet(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CacheSetMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CacheSet>>>
    export type PostApiV1CacheSetMutationBody = RedisCacheRequest
    export type PostApiV1CacheSetMutationError = AxiosError<BooleanServiceResult>

    export const usePostApiV1CacheSet = <TError = AxiosError<BooleanServiceResult>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CacheSet>>, TError,{data: RedisCacheRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CacheSet>>,
        TError,
        {data: RedisCacheRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1CacheSetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    