/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Shopping Project API
 * Shopping Project API documentation
 * OpenAPI spec version: 1.0
 */
export interface AuthResponse {
  /** @nullable */
  accessToken?: string | null;
  /** @nullable */
  refreshToken?: string | null;
  expires?: string;
}

export interface AuthResponseServiceResult {
  isSuccess?: boolean;
  data?: AuthResponse;
  /** @nullable */
  message?: string | null;
  statusCode?: HttpStatusCode;
  /** @nullable */
  location?: string | null;
}

export interface BooleanServiceResult {
  isSuccess?: boolean;
  data?: boolean;
  /** @nullable */
  message?: string | null;
  statusCode?: HttpStatusCode;
  /** @nullable */
  location?: string | null;
}

export interface CartDto {
  id?: number;
  /** @nullable */
  title?: string | null;
  price?: number;
  /** @nullable */
  image?: string | null;
  quantity?: number;
  /** @nullable */
  ownerId?: string | null;
}

export interface CartDtoListServiceResult {
  isSuccess?: boolean;
  /** @nullable */
  data?: CartDto[] | null;
  /** @nullable */
  message?: string | null;
  statusCode?: HttpStatusCode;
  /** @nullable */
  location?: string | null;
}

export interface CartDtoServiceResult {
  isSuccess?: boolean;
  data?: CartDto;
  /** @nullable */
  message?: string | null;
  statusCode?: HttpStatusCode;
  /** @nullable */
  location?: string | null;
}

export interface CreateCartCommand {
  /** @nullable */
  ownerId?: number | null;
  quantity?: number;
  /** @nullable */
  title?: string | null;
  price?: number;
  /** @nullable */
  image?: string | null;
}

export interface CreateProductCommand {
  /** @nullable */
  title?: string | null;
  price?: number;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  category?: string | null;
  /** @nullable */
  image?: string | null;
}

export interface DynamicQuery {
  /** @nullable */
  sort?: Sort[] | null;
  filter?: Filter;
}

export interface Filter {
  /** @nullable */
  field?: string | null;
  /** @nullable */
  value?: string | null;
  /** @nullable */
  operator?: string | null;
  /** @nullable */
  logic?: string | null;
  /** @nullable */
  filters?: Filter[] | null;
}

export interface ForgotPasswordCommand {
  /** @nullable */
  email?: string | null;
}

export type HttpStatusCode = typeof HttpStatusCode[keyof typeof HttpStatusCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HttpStatusCode = {
  NUMBER_100: 100,
  NUMBER_101: 101,
  NUMBER_102: 102,
  NUMBER_103: 103,
  NUMBER_200: 200,
  NUMBER_201: 201,
  NUMBER_202: 202,
  NUMBER_203: 203,
  NUMBER_204: 204,
  NUMBER_205: 205,
  NUMBER_206: 206,
  NUMBER_207: 207,
  NUMBER_208: 208,
  NUMBER_226: 226,
  NUMBER_300: 300,
  NUMBER_301: 301,
  NUMBER_302: 302,
  NUMBER_303: 303,
  NUMBER_304: 304,
  NUMBER_305: 305,
  NUMBER_306: 306,
  NUMBER_307: 307,
  NUMBER_308: 308,
  NUMBER_400: 400,
  NUMBER_401: 401,
  NUMBER_402: 402,
  NUMBER_403: 403,
  NUMBER_404: 404,
  NUMBER_405: 405,
  NUMBER_406: 406,
  NUMBER_407: 407,
  NUMBER_408: 408,
  NUMBER_409: 409,
  NUMBER_410: 410,
  NUMBER_411: 411,
  NUMBER_412: 412,
  NUMBER_413: 413,
  NUMBER_414: 414,
  NUMBER_415: 415,
  NUMBER_416: 416,
  NUMBER_417: 417,
  NUMBER_421: 421,
  NUMBER_422: 422,
  NUMBER_423: 423,
  NUMBER_424: 424,
  NUMBER_426: 426,
  NUMBER_428: 428,
  NUMBER_429: 429,
  NUMBER_431: 431,
  NUMBER_451: 451,
  NUMBER_500: 500,
  NUMBER_501: 501,
  NUMBER_502: 502,
  NUMBER_503: 503,
  NUMBER_504: 504,
  NUMBER_505: 505,
  NUMBER_506: 506,
  NUMBER_507: 507,
  NUMBER_508: 508,
  NUMBER_510: 510,
  NUMBER_511: 511,
} as const;

export interface Int32ServiceResult {
  isSuccess?: boolean;
  data?: number;
  /** @nullable */
  message?: string | null;
  statusCode?: HttpStatusCode;
  /** @nullable */
  location?: string | null;
}

export interface LoginCommand {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  [key: string]: unknown;
}

export interface ProductDto {
  id?: number;
  /** @nullable */
  title?: string | null;
  price?: number;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  category?: string | null;
  /** @nullable */
  image?: string | null;
  rating?: RatingDto;
}

export interface ProductDtoIEnumerableServiceResult {
  isSuccess?: boolean;
  /** @nullable */
  data?: ProductDto[] | null;
  /** @nullable */
  message?: string | null;
  statusCode?: HttpStatusCode;
  /** @nullable */
  location?: string | null;
}

export interface ProductDtoIPaginate {
  readonly from?: number;
  readonly index?: number;
  readonly size?: number;
  readonly count?: number;
  readonly pages?: number;
  /** @nullable */
  readonly items?: readonly ProductDto[] | null;
  readonly hasPrevious?: boolean;
  readonly hasNext?: boolean;
}

export interface ProductDtoIPaginateServiceResult {
  isSuccess?: boolean;
  data?: ProductDtoIPaginate;
  /** @nullable */
  message?: string | null;
  statusCode?: HttpStatusCode;
  /** @nullable */
  location?: string | null;
}

export interface ProductDtoPaginatedList {
  /** @nullable */
  items?: ProductDto[] | null;
  pageNumber?: number;
  readonly totalPages?: number;
  readonly totalCount?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
}

export interface ProductDtoPaginatedListServiceResult {
  isSuccess?: boolean;
  data?: ProductDtoPaginatedList;
  /** @nullable */
  message?: string | null;
  statusCode?: HttpStatusCode;
  /** @nullable */
  location?: string | null;
}

export interface ProductDtoServiceResult {
  isSuccess?: boolean;
  data?: ProductDto;
  /** @nullable */
  message?: string | null;
  statusCode?: HttpStatusCode;
  /** @nullable */
  location?: string | null;
}

export interface RatingDto {
  rate?: number;
  count?: number;
}

export interface RedisCacheRequest {
  /** @nullable */
  key?: string | null;
  /** @nullable */
  value?: string | null;
}

export interface RefreshTokenCommand {
  /** @nullable */
  accessToken?: string | null;
  /** @nullable */
  refreshToken?: string | null;
}

export interface RegisterCommand {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  role?: string | null;
}

export interface ResetPasswordCommand {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  token?: string | null;
  /** @nullable */
  newPassword?: string | null;
}

export interface Sort {
  /** @nullable */
  field?: string | null;
  /** @nullable */
  dir?: string | null;
}

export interface StringServiceResult {
  isSuccess?: boolean;
  /** @nullable */
  data?: string | null;
  /** @nullable */
  message?: string | null;
  statusCode?: HttpStatusCode;
  /** @nullable */
  location?: string | null;
}

export interface UpdateCartCommand {
  id?: number;
  /** @nullable */
  title?: string | null;
  price?: number;
  /** @nullable */
  image?: string | null;
  quantity?: number;
}

export interface UpdateMeCommand {
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  gender?: string | null;
}

export interface UpdateProductCommand {
  id?: number;
  /** @nullable */
  title?: string | null;
  price?: number;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  image?: string | null;
  /** @nullable */
  category?: string | null;
}

export interface UserInfoResponse {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  roles?: string[] | null;
}

export interface UserInfoResponseServiceResult {
  isSuccess?: boolean;
  data?: UserInfoResponse;
  /** @nullable */
  message?: string | null;
  statusCode?: HttpStatusCode;
  /** @nullable */
  location?: string | null;
}

export type GetApiV1ProductsPagedParams = {
pageNumber?: number;
pageSize?: number;
};

export type PostApiV1ProductsSearchParams = {
index?: number;
size?: number;
};

